const env = require('../config/env');

let transporter = null;

function getTransporter() {
  if (!env.smtp.configured) return null;
  if (transporter) return transporter;
  // Lazy-require so the package is optional at runtime if SMTP is never configured.
  const nodemailer = require('nodemailer');
  transporter = nodemailer.createTransport({
    host: env.smtp.host,
    port: env.smtp.port,
    secure: env.smtp.port === 465,
    auth: { user: env.smtp.user, pass: env.smtp.pass },
  });
  return transporter;
}

/**
 * Sends the "reset your password" email containing a one-time link.
 * In dev mode (no SMTP configured) this just logs the link to the server
 * console instead of failing, so the reset flow stays testable without
 * real email credentials — no SMS/OTP fallback is used anywhere.
 */
async function sendPasswordResetEmail({ to, name, resetUrl }) {
  const subject = 'ধোপা বাড়ি — পাসওয়ার্ড রিসেট করুন';
  const html = `
    <div style="font-family:sans-serif;max-width:480px;margin:0 auto">
      <h2 style="color:#1259E8">ধোপা বাড়ি</h2>
      <p>হ্যালো ${name || ''},</p>
      <p>আপনার অ্যাকাউন্টের পাসওয়ার্ড রিসেট করার অনুরোধ পাওয়া গেছে। নিচের বাটনে ক্লিক করে নতুন পাসওয়ার্ড সেট করুন। এই লিংকটি ${env.resetPassword.tokenTtlMinutes} মিনিটের জন্য কার্যকর থাকবে।</p>
      <p><a href="${resetUrl}" style="display:inline-block;background:#1259E8;color:#fff;padding:12px 20px;border-radius:8px;text-decoration:none;font-weight:700">পাসওয়ার্ড রিসেট করুন</a></p>
      <p style="color:#66748F;font-size:12px">আপনি যদি এই অনুরোধ না করে থাকেন, তাহলে এই ইমেইলটি উপেক্ষা করুন।</p>
    </div>`;

  const t = getTransporter();
  if (!t) {
    console.log(`[email:dev-mode] would send password reset email to ${to}: ${resetUrl}`);
    return { sent: false, reason: 'smtp-not-configured', resetUrl };
  }
  await t.sendMail({ from: `"${env.smtp.fromName}" <${env.smtp.fromEmail}>`, to, subject, html });
  return { sent: true };
}

/**
 * Emails a receipt PDF (pickup or delivery) as an attachment. The PDF is
 * rendered client-side — this only relays the already-generated bytes, so
 * there is exactly one receipt layout implementation, not one per platform.
 * In dev mode (no SMTP configured) this logs instead of failing.
 */
async function sendReceiptEmail({ to, receiptNumber, pdfBase64 }) {
  const subject = `ধোপা বাড়ি — রিসিট ${receiptNumber}`;
  const html = `
    <div style="font-family:sans-serif;max-width:480px;margin:0 auto">
      <h2 style="color:#1259E8">ধোপা বাড়ি</h2>
      <p>আপনার রিসিট (${receiptNumber}) সংযুক্ত করা হয়েছে।</p>
    </div>`;

  const t = getTransporter();
  if (!t) {
    console.log(`[email:dev-mode] would email receipt ${receiptNumber} to ${to}`);
    return { sent: false, reason: 'smtp-not-configured' };
  }
  await t.sendMail({
    from: `"${env.smtp.fromName}" <${env.smtp.fromEmail}>`,
    to,
    subject,
    html,
    attachments: [{ filename: `${receiptNumber}.pdf`, content: Buffer.from(pdfBase64, 'base64'), contentType: 'application/pdf' }],
  });
  return { sent: true };
}

module.exports = { sendPasswordResetEmail, sendReceiptEmail };
